version: '1'

services:
  app:
    container_name: ts-node-app
    build: 
      context: .
      dockerfile: Dockerfile
      target: base
    restart: always
    env_file: .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    environment: 
      - MONGODB_URL=${MONGODB_URL}
      - CLIENT_URL=${CLIENT_URL}
    links: 
      - mongo  
    depends_on:
      - mongo  
    networks:
      - backend

networks:
  backend:
    driver: bridge    
