version: '3'

services:
  app:
    container_name: todo-app
    build: 
      context: .
      dockerfile: Dockerfile
      target: base
    restart: always
    env_file: .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    environment: 
      - MONGODB_URL=${MONGODB_URL}
      - CLIENT_URL=${CLIENT_URL}