version: '3'

services:
  app:
    container_name: todo-app
    image: ${DOCKER_USERNAME}/todo-app:latest
    build: 
      target: production
    command: yarn start
    environment:
    - NODE_ENV=production

