name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - .github/workflows/**

jobs:
#   build:
#     runs-on: ubuntu-latest
#     environment: Production

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build Docker image
#         run: |
#           docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-app:latest ./backend

#       - name: Push Docker image
#         run: |
#           docker push ${{ secrets.DOCKER_USERNAME }}/todo-app:latest

  deploy:
    runs-on: ubuntu-latest
    # needs: build

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Deploy to Server
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            PORT: ${{ secrets.PORT }}
            DOMAIN: ${{ secrets.DOMAIN }}      
            SERVER_SSH_PORT:    ${{ secrets.SERVER_SSH_PORT }}
          run: |
            sudo apt-get install sshpass -y
            sshpass -p "${SSH_PASSWORD}" ssh -o StrictHostKeyChecking=no root@${DOMAIN} -p ${SERVER_SSH_PORT} "
            docker pull ${DOCKER_USERNAME}/todo-app:latest &&
            docker stop todo-app-prod || true &&
            docker rm todo-app-prod || true &&
            docker run -d --name todo-app-prod -p ${PORT}:${PORT} ${DOCKER_USERNAME}/todo-app:latest
            "

